name: Build and Release Browser Extensions

on:
  push:
    tags:
      - v*

jobs:
  build_firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
      - name: Install packages (`pnpm i`)
        run: pnpm i
      - name: Build Firefox extension
        env:
          VERSION: ${{ github.ref_name }}
        run: pnpm run build:firefox
      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension-${{ github.ref_name }}
          path: ./dist/extension/*

  build_chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
      - name: Install packages (`pnpm i`)
        run: pnpm i
      - name: Build Chrome extension
        env:
          VERSION: ${{ github.ref_name }}
        run: pnpm run build:chrome
      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ github.ref_name }}
          path: ./dist/extension/*

  release_firefox:
    needs: build_firefox
    runs-on: ubuntu-latest
    steps:
      - name: Download Firefox artifact
        uses: actions/download-artifact@v4
        with:
          name: firefox-extension-${{ github.ref_name }}
          path: ./
      - name: List Artifacts
        run: ls ./
      - name: Create Firefox Release
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: shikivost@cjvnjde.com
          xpi-path: ./firefox-extension-${{ github.ref_name }}.zip
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}

  release_chrome:
    needs: build_chrome
    runs-on: ubuntu-latest
    steps:
      - name: Download Chrome artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension-${{ github.ref_name }}
          path: ./
      - name: List Artifacts
        run: ls ./
      - name: Create Chrome Release
        uses: wdzeng/chrome-extension@v1
        with:
          extension-id: alfpkdagonppegpjijmcgcccafchklmc
          zip-path: ./chrome-extension-${{ github.ref_name }}.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
