name: Build and Release Browser Extensions

on:
  push:
    tags:
      - v*

jobs:
  build_firefox:
    name: "Build Firefox"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
      - name: Install packages (`pnpm i`)
        run: pnpm i
      - name: Build Firefox extension
        env:
          VERSION: ${{ github.ref_name }}
        run: pnpm run build:firefox
      - name: Bundle Firefox extension
        run: pnpm run bundle
      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension-${{ github.ref_name }}
          path: ./dist/*.zip
          compression-level: 0

  build_chrome:
    name: "Build Chrome"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
      - name: Install packages (`pnpm i`)
        run: pnpm i
      - name: Build Chrome extension
        env:
          VERSION: ${{ github.ref_name }}
        run: pnpm run build:chrome
      - name: Bundle Chrome extension
        run: pnpm run bundle
      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ github.ref_name }}
          path: ./dist/*.zip
          compression-level: 0

  release_firefox:
    name: "Release Firefox"
    needs: [build_firefox, build_chrome]
    runs-on: ubuntu-latest
    steps:
      - name: Download Firefox artifact
        uses: actions/download-artifact@v4
        with:
          name: firefox-extension-${{ github.ref_name }}
          path: ./
      - name: Create Firefox Release
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: shikivost@cjvnjde.com
          xpi-path: ./shikivost-*.zip
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}

  release_chrome:
    name: "Release Chrome"
    needs: build_chrome
    runs-on: ubuntu-latest
    steps:
      - name: Download Chrome artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension-${{ github.ref_name }}
          path: ./
      - name: Create Chrome Release
        uses: wdzeng/chrome-extension@v1
        with:
          extension-id: alfpkdagonppegpjijmcgcccafchklmc
          zip-path: ./shikivost-*.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

  create_release:
      name: "Create GitHub Release"
      runs-on: ubuntu-latest

      steps:
        - name: Download Chrome artifact
          uses: actions/download-artifact@v4
          with:
            name: chrome-extension-${{ github.ref_name }}
            path: ./
        - name: Download Firefox artifact
          uses: actions/download-artifact@v4
          with:
            name: firefox-extension-${{ github.ref_name }}
            path: ./
        - uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            files: |
              *.zip